-d Q:\gr_picorv32_soc\project\impl\gwsynthesis\picotiny.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst Q:\gr_picorv32_soc\project\picorv32_soc_top.cst
-cfg Q:\gr_picorv32_soc\project\impl\pnr\device.cfg
-sdc Q:\gr_picorv32_soc\project\picorv32_soc_top.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
