-d Q:\gr_picorv32_soc\hw\led_mux\led_mux\impl\gwsynthesis\led_mux.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cfg Q:\gr_picorv32_soc\hw\led_mux\led_mux\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
